language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WVZlDfxuruh84iNfA7B2sD3RCtcOc96GVtLTKgCJXNzE8TvEJYeRpNZZ7snay37XkZNCpSdTVIOeZd3k/mYKpeHnOEEcTxDor4+aegI7VU8CK5C3+NiBhBejj4oh6gLsykOV9hmqhDvDxtdGPBkFNnghDXpIKUnSmgEaVoWnKLyoy7V/EzVZqaobdwneYqX4Me/y8MEK34oCufll7rC+pnBTolednaVK9hiEB+XKmrZy1rmWqJhsfx1O6pst8R1Sm7nwPaM8xv32/oA8PDDr7hLxG0CGYxcxfWzyR+yEkR4aECmkp74IM8Vd9NdaZ4AWUnTtaYcieLudS1k8+CmO3/De8Qn1yqR/GVGQDYT+7TBuSfZMAOmvqZKAX39WyY0LxZrRFZXpd5NXdgQPDlFu4Wun3T1VGYSezOYKrVqe3hQIAn/HKfMQ6M5z/H6R3Q/fAvCxWDcljh8ITzZcZ3HXOUQkbkvTyps1MFuA2O7eC9EOd0z1PzyOaTkukPArrU8kUIGWLAVZzA2yj2YWG19brIDXEBjP0TBugKAdvNw55HrzapfNkVRpML5bEuISpWcRKVV0/eYdy0cLBmhEuDDsd4Z2BpgssIgo5xXFggkmNvfeLwrXfwZHbzQddkO66xOp2qRhGvAIIHkFqZUvKIVE6fEw0Z2EIpPwEUAnArLlMMs=
  app: sleepy-chamber-65901
  on:
    repo: vcordero07/blog-api
